import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import Member from '@/components/Member'
import styled from 'js-styled'

const jss = styled(`
  memberEx {

    & h2 {
      font-family: 'Lobster', cursive;
      font-size: 48px;
      text-shadow: 0 0 40px black;
    }
    & p {
      font-family: 'Italianno', cursive;
      font-size: 32px;
    }
  }
`)

export default function Home() {

  const classes = jss()

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Member className={classes.memberEx}/>
      </main>
    </>
  )
}
