import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import Member from '@/components/Member'
import styled from 'styled-components'

const MemberEx = styled(Member)`
  width: 300px;
`

export default function Home() {

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <MemberEx/>
      </main>
    </>
  )
}
